-- create table if not exists tempusers(
-- 	id serial primary key,
-- 	email varchar(256) unique not null,
-- 	username varchar(100) unique not null,
-- 	password text not null,
-- 	verified boolean default false
-- );

-- create table if not exists users(
-- 	id serial primary key,
-- 	email varchar(256) unique not null,
-- 	username varchar(100) unique not null,
-- 	password text not null
-- );
